### ISSUE TITLE
All parameters are saved using repr instead of str in hdf5 after recent updates

### ISSUE THREAD

**Issue by antsr** [QudevETH/PycQED_py3#17]
This is undesired as it breaks much of existing analysis code.

The fix for now is to revert `measurement_control.py` line 1161:
```python
for (p_name, p) in parameter_list:
    try:
        val = repr(p['value'])
    except KeyError:
        val = ''
    instrument_grp.attrs[p_name] = val
```
to
```python
for (p_name, p) in parameter_list:
    try:
        val = str(p['value'])
    except KeyError:
        val = ''
    instrument_grp.attrs[p_name] = val
```

But this might break saving of list parameters (e.g. readout freq. for multichromatic pulse)

**Comment by stephlazar** [comment]
Clarification: all instrument settings were saved a string before as well my bad, I got confused here). But now they are saved as repr. This is bad because it breaks string recognition: repr('hello') == 'hello' or str(repr('hello')) == 'hello' both return False! This breaks several parts of the analyses.

**Comment by nathlacroix** [comment]
That is surprizing, I didn't encounter any issue with the analysis so far using `repr`. Could the encountered errors be described more precisely? 

A priori, without additional information about the issue, I strongly believe we should **not** revert this but rather adapt the rest of the code such that saving representation works. Here is why:

1) Representation does not break string recognition. While `str(repr("hello")) == "hello"` returns `False`, `eval(repr("hello")) == "hello"` returns `True` as expected.

2) To quote the official [Python documentation](https://docs.python.org/3/library/stdtypes.html#str), str is meant to be use for:

> an informal or nicely printable string representation of an object.

i.e. not a unique representation of the object. This is why `str(my_long_array)` returns only a truncated version of the array, and prevents the saving of dictionaries, lists, and arrays. On the other hand, `repr `is meant to be an unambiguious (i.e. unique) representation of an object, that can (if possible) be recontructed unambigiously and solely from its representation (cf. https://docs.python.org/3/library/functions.html#repr).  This is the purpose we seek when saving experiment parameters.

3) Using `repr` to save objects such as calibration points is really easy, as long as the `__repr__(self)` function is defined in the class. One can simply do: `exp_metadata.update(dict(cal_points=cp))` where `cp` is a calibration point object. Same for Sweeppoint object or any other class that we create and would like to save for the analysis. By doing this, we could even save sequences, etc. With proper data loading, these objects would also automatically be reconstructed when loading the hdf5 files, avoiding the unnecessary rebuilding from representation within the analysis.

4) Using representation, all the clumsy code of the parameters reloading which has N try-except clauses for each possible value type could be replaced by a single try-catch clause using eval:
```
 if value == 'None':  # None is saved as string in hdf5
                       try:
                           instrument.set(parameter, None)
                       except Exception:
                           print('Could not set parameter "%s" to "%s" for '
                                 'instrument "%s"' % (
                                     parameter, value, instrument_name))
                   elif value == 'False':
                       try:
                           instrument.set(parameter, False)
                       except Exception:
                           print('Could not set parameter "%s" to "%s" for '
                                 'instrument "%s"' % (
                                     parameter, value, instrument_name))
                   elif value == 'True':
                       try:
                           instrument.set(parameter, True)
                       except Exception:
                           print('Could not set parameter "%s" to "%s" for '
                                 'instrument "%s"' % (
                                     parameter, value, instrument_name))
                   else:
                       try:
                           instrument.set(parameter, int(value))
                       except Exception:
                           try:
                               instrument.set(parameter, float(value))
                           except Exception:
                               try:
                                   instrument.set(parameter, eval(value))
                               except Exception:
                                   try:
                                       instrument.set(parameter,
                                                      value)
                                   except Exception:
                                       log.error('Could not set parameter '
                                             '"%s" to "%s" '
                                             'for instrument "%s"' % (
                                                 parameter, value,
                                                 instrument_name))
```
Would simply become:

```
try:
    instrument.set(parameter, eval(value))
except Exception:
    log.error(f"Could not set {parameter} to {value}")
```

Similar code can be used in the base analysis data extraction, which should solve any string recognition issue encountered using `str`.

The one point to keep in mind, when using `eval `, is that we need to trust the file we are loading, ie. that it does not contain a virus. But since we produce the hfd5 ourselves, this should not be of a big concern (eval is also used elsewhere in the framework).

Finally, adapting the analysis code should require very little overhead as we can just adapt the data loading function :) 

I am of course available to help adapting the loading function if I get a bit more details on where the problem arises.
