### ISSUE TITLE
Check for single segment on master AWG

### ISSUE THREAD

**Issue by michele-cc** [QudevETH/PycQED_py3#6]
self._test_trigger_awg()
is incompatible with using only a single AWG, as the master AWG will then also play all qubit pulses

line 331 in segment.py

**Comment by antsr** [comment]
`self._test_trigger_awg()` should not be the issue here, as it just checks that if an AWG is not triggered by a marker channel registered in pulsar (meaning it is triggered by the function generator in your case), that it has only a single element (=waveform for each channel) per segment (=subexperiment) on it. This comes from the hardware constraint that we don't have precise timing control over the triggers that arrive at the AWG, meaning we have to put everything in a single waveform.

The real issue is #4. If that is solved, then `self._test_trigger_awg()` should work as it is.

@michele-cc Please close this issue if you agree with my understanding of the issue.
